name: Cypress Tests with Docker

on: # Define quando o workflow será executado
  push: # Ao fazer push
    branches: [main] # Apenas na branch main
  pull_request: # Ou ao abrir pull request
    branches: [main] # Apenas na branch main

jobs:
  cypress-docker: # Nome do job
    runs-on: ubuntu-latest # Runner do GitHub (máquina virtual Ubuntu)

    steps:
      - name: Checkout code # Passo 1: Faz checkout do código do repositório
        uses: actions/checkout@v3

      - name: Build Docker image # Passo 2: Builda a imagem Docker do projeto
        run: docker build -t cypress-tests .

      - name: Run Cypress tests in Docker # Passo 3: Executa os testes dentro do container Docker
        run: docker run --rm cypress-tests

      - name: Upload test reports # Passo 4: (Opcional) Faz upload dos relatórios de teste como artefato
        if: always() # Sempre executa, mesmo se algum passo anterior falhar
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reports # Nome do artefato
          path: cypress/reports # Caminho dos relatórios gerados